---
title: "ORDER BY in Window Functions"
output: github_document
---

## ORDER BY

* Assign a number to each year in which Summer Olympic games were held so that rows with the most recent years have lower row numbers.


```{sql eval=FALSE}
SELECT
  Year,
  -- Assign the lowest numbers to the most recent years
  ROW_NUMBER() OVER (ORDER BY Year DESC) AS Row_N
FROM (
  SELECT DISTINCT Year
  FROM Summer_Medals
) AS Years
ORDER BY Year;
```

* `ORDER BY` is a subclause of `OVER`
* It orders the rows related to the current row that the window function will use.

## Reigning champion

* One of the applications of window functions is determining reigning champion status. A reigning champion is a champion who's **won both the previous and current years' competitions**. To determine if a champion is a reigning champion, the previous and the current years' champions need to be in the same row, in two different columns, so that they can be compared. How can you get a previous row's value without complex self-joins? 

* Enter `LAG`. `LAG` is a window function that takes a column and a number n and returns the column's value n rows before the current row. Passing 1 as n returns the previous row's value.


```{r cars}