---
title: "Frames"
output: github_document
---

## Motivation
* RANGE BETWEEN 
* ROWS BETWEEN

### RANGE BETWEEN

*frame always has a start and a finish. Start and finish can be one of 3 clauses: PRECEDING, CURRENT ROW, and FOLLOWING n PRECEDING defines the frame as either starting or finishing n rows before the current row

* Frames allow you to restrict the rows passed as input to your window function to a sliding window for you to define the start and finish.

* Adding a frame to your window function allows you to calculate "moving" metrics, inputs of which slide from row to row.

#### Exercise 1 - Moving maximum of Scandinavian athletes' medals

```{sql eval=FALSE}
WITH Scandinavian_Medals AS (
  SELECT
    Year, COUNT(*) AS Medals
  FROM Summer_Medals
  WHERE
    Country IN ('DEN', 'NOR', 'FIN', 'SWE', 'ISL')
    AND Medal = 'Gold'
  GROUP BY Year)

SELECT
  -- Select each year's medals
  Year,
  Medals,
  -- Get the max of the current and next years'  medals
  MAX(Medals) OVER (ORDER BY Year ASC
                    ROWS BETWEEN CURRENT ROW
                    AND 1 FOLLOWING) AS Max_Medals
FROM Scandinavian_Medals
ORDER BY Year ASC;
```

#### Exercise 2 - Moving maximum of Chinese athletes' medals

* Return the athletes, medals earned, and the maximum medals earned, comparing only the last two and current athletes, ordering by athletes' names in alphabetical order.

```{sql eval=FALSE}
WITH Chinese_Medals AS (
  SELECT
    Athlete, COUNT(*) AS Medals
  FROM Summer_Medals
  WHERE
    Country = 'CHN' AND Medal = 'Gold'
    AND Year >= 2000
  GROUP BY Athlete)

SELECT
  -- Select the athletes and the medals they've earned
  Athlete,
  Medals,
  -- Get the max of the last two and current rows' medals 
  MAX(Medals) OVER (ORDER BY Athlete ASC
                    ROWS BETWEEN 2 PRECEDING
                    AND CURRENT ROW) AS Max_Medals
FROM Chinese_Medals
ORDER BY Athlete ASC;
```

