---
title: "Sub-Queries"
output: github_document
---

## Nested Queries

### Within `WHERE` clause

#### **Exercise 1** 

* A. Begin by calculating the average life expectancy across all countries for 2015.

```{sql eval=FALSE}
-- Select average life_expectancy
Select AVG(life_expectancy)
  -- From populations
  FROM populations
-- Where year is 2015
Where year = '2015'
```

* You'll now try to figure out which countries had high average life expectancies (at the country level) in 2015.

Recall that you can use SQL to do calculations for you. Suppose we wanted only records that were above `1.15 * 100` in terms of life expectancy for 2015.

```{sql eval=FALSE}
SELECT *
  FROM populations
WHERE life_expectancy > 1.15 * 100
  AND year = 2015;
```

Then you can plug it into a `WHERE` clause and that's it:

```{sql eval=FALSE}
-- Select fields
SELECT *
  -- From populations
  FROM populations
-- Where life_expectancy is greater than
WHERE life_expectancy >
  -- 1.15 * subquery
  1.15 * (SELECT AVG(life_expectancy)
   FROM populations
   WHERE year = 2015) AND
  year = 2015;```
```

* B. Use your knowledge of subqueries in `WHERE` to get the urban area population for only capital cities.

```{sql eval=FALSE}
-- Select fields
SELECT name, country_code, urbanarea_pop
  -- From cities
  FROM cities
-- Where city name in the field of capital cities
WHERE name IN
  -- Subquery
  (SELECT capital
   FROM countries)
ORDER BY urbanarea_pop DESC;
```


### Within `SELECT` clause
#### **Exercise 2** 

* Convert the `GROUP BY` code to use a subquery inside of `SELECT` by filling in the blanks to get a result that matches the one given using the `GROUP BY` code in the first query.

```{sql eval=FALSE}
/*
SELECT countries.name AS country,
COUNT(*) AS cities_num
  FROM cities
    INNER JOIN countries
    ON countries.code = cities.country_code
GROUP BY country
ORDER BY cities_num DESC, country
LIMIT 9;
*/

SELECT countries.name AS country,
  -- Subquery
  (SELECT count(*)
   FROM cities
   WHERE countries.code = cities.country_code) AS cities_num
FROM countries
ORDER BY cities_num DESC, country
LIMIT 9;
```

### Within `FROM` clause
#### **Exercise 3** 



